curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
sudo dpkg -i cloudflared.deb
sudo cloudflared service install eyJhIjoiMmYzODFmNzMwMDQ1YTMyNDYxNmMyMDgwMjRhMjdkZWQiLCJ0IjoiNmE0ZmI1MzMtN2MzOC00Yjg3LTg0MjctYWY3NDM0M2Y5YTUxIiwicyI6IlkyWmhOVFJtTkRrdFlqRmlZeTAwTjJVeExUZ3hZbVF0WVRjME1tVmlaVE00TUdWbSJ9
