curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
sudo dpkg -i cloudflared.deb
sudo cloudflared service install eyJhIjoiMmYzODFmNzMwMDQ1YTMyNDYxNmMyMDgwMjRhMjdkZWQiLCJ0IjoiNGQyZTZlZDgtNmNhZS00ZGI3LTg5MTgtNzcwMTJlMTFiMjdmIiwicyI6Ik9HSXdOVEptWm1VdFlqbGhaUzAwWTJaaUxUazNZemt0WTJFMU0yTTBNemszTUdZNSJ9
