# THIS CONFIG IS INVALID. USING IT WILL NOT WORK.

debug: false
uuid: ff5e0002-f1a4-4fe8-a012-0bf43a0b918d
token_id: EjqSWgss0rXBJ9Mu
token: GV4HLtRq3yMvPMSlx9lfpvmIh6hS2228zZkAr7TApMVfEhfZ6Cre22Djo3f3GTey
api:
  host: 0.0.0.0
  port: 8080
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://hosting.sockycat.net'
